# -*- coding: utf-8 -*-
"""systematic_literature_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Sc4fn5bdhnvA7aExEnJgWiX7c7ThQFt

Author: Sofia Midauar

Date: April 2023
"""

# !pip install geopandas
# !pip install country_converter

import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np
from matplotlib import rc
import time
import seaborn as sns
import matplotlib.ticker as mtick
from matplotlib.gridspec import GridSpec

# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# --- Path setup (added for repository use) ---------------------------------
# Original notebook read from a hardcoded Google Drive / Colab path. Data now
# loads from the local `data/` folder relative to this script. Outputs are
# written to `figures/`. No analysis logic was changed.
import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
DATA_DIR = os.path.join(BASE_DIR, "data")
FIG_DIR = os.path.join(BASE_DIR, "figures")
os.makedirs(FIG_DIR, exist_ok=True)
# ---------------------------------------------------------------------------


# Import files
review_complete = pd.read_excel(os.path.join(DATA_DIR, 'database_papers_updated_format.xlsx'))

review_complete.head()

# Create subset with one row per paper
review_papers = review_complete[review_complete['id'].notna()] # excludes rows with NA values in ID column
review_papers
# review_papers.head()

# Check distribution of number of citations per publication
# review_papers['citations'].hist()

"""# Subset of database: review papers excluded"""

# Create subset without review papers
db_noreviews = review_complete[(review_complete['review'] != 'Yes') & (review_complete['publication_type'] != 'Book chapter')]
db_noreviews.head()

lakes_coords = db_noreviews[['id', 'evidence_type', 'country', 'latitude_N', 'longitude_E']]
lakes_coords.dropna(inplace = True)
# lakes_coords = lakes_coords[(lakes_coords['evidence_type'] != 'Modelled') & (lakes_coords['latitude_N'] != 'varies')]
lakes_coords = lakes_coords[(lakes_coords['latitude_N'] != 'varies') & (lakes_coords['latitude_N'] != 'Multiple')]
lakes_coords

lakes_coords.to_csv(os.path.join(DATA_DIR, 'lakes_coords.csv'))

from shapely.geometry import Point
import geopandas as gpd
from geopandas import GeoDataFrame

geometry = [Point(xy) for xy in zip(lakes_coords['longitude_E'], lakes_coords['latitude_N'])]
gdf = GeoDataFrame(lakes_coords, geometry=geometry)

#this is a simple map that goes with geopandas
# NOTE: gpd.datasets was removed in GeoPandas 1.0 (2024). On newer
# versions this line will fail. Provide a Natural Earth shapefile
# locally and point gpd.read_file() at it instead. See README.
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf.plot(ax=world.plot(figsize=(10, 6)), marker='o', color='k', markersize=15);

"""# Barplot of publications per year and reviews"""

# Get number of publications per year
years = review_papers['year'].value_counts()
years = pd.DataFrame(years)
years = years.reset_index()
years.rename(columns = {'year':'years'}, inplace = True)
years = years.sort_values(by = ['years'])
years['years'] = years['years'].astype(int)

# Add info: which of those are reviews?
year_review = years['years']
reviews = [0,1,1,1,2,1,4,3,0,0] # manually estimated in excel
years['reviews'] = reviews

# Add 2015
new_row = {'years':2015, 'count':0, 'reviews':0}
years.loc[len(years)] = new_row
years = years.sort_values(by = ['years'])

# Add column with cumulative sum
years['count_cum_sum'] = years['count'].cumsum()

years

# barplot
fig, ax = plt.subplots(nrows=1, ncols=1, figsize=[7.2,3.5])

# plot
barWidth = 0.7

ax.bar(years['years'], years['count'], color='#8E8E8E', edgecolor='white', width=barWidth, label = 'Primary research')
ax.bar(years['years'], years['reviews'], color='#515151', edgecolor='white', width=barWidth, label = 'Synthesis')

ax2 = ax.twinx()

ax2.plot(years['years'], years['count_cum_sum'], color='k', label = "Cumulative count")
ax2.set_ylabel("Cumulative count", size = 12)

xlabels = years['years']
ax.set_xticks(years['years'])
ax.set_xticklabels(years['years'])
ax.set_ylabel("Publication count", size = 12)
ax.set_xlabel("Year", size = 12)
# ax.legend(loc = 'upper left')

lines, labels = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc = 'upper left')

ax.set_axisbelow(True)
ax.grid(color='lightgray', axis = 'y')

# Plot adjustments
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)

plt.tight_layout()

# Save graph
plt.savefig(os.path.join(FIG_DIR, 'publications_yearly_distribution_updated.jpg'), format = 'jpeg', dpi=300);

# barplot
fig, ax = plt.subplots(nrows=1, ncols=1, figsize=[6,3.5])

# plot
barWidth = 0.7

ax.plot(years['years'], years['count_cum_sum'], color='#515151')

xlabels = years['years']
ax.set_xticks(years['years'])
ax.set_xticklabels(years['years'])
ax.set_ylabel("Number of publications", size = 12)
ax.set_xlabel("Year", size = 12)

ax.set_axisbelow(True)
ax.grid(color='lightgray', axis = 'y')

# Plot adjustments
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)

plt.tight_layout()

# Save graph
# plt.savefig('cumulative_plot_publications.png', format = 'png', dpi=300);

"""# Percentage of review papers"""

# Get number of publications per year
perc_review = review_papers['review'].value_counts()
perc_review = pd.DataFrame(perc_review)
perc_review = perc_review.reset_index()
# perc_review.rename(columns = {'index':'review', 'review':'count'}, inplace = True)
perc_review

# Create a circle at the center of the plot
# plt.switch_backend('agg') # line to export figure
fig, ax = plt.subplots()
pub_type_circle = plt.Circle((0,0), 0.6, color='white')

# Give color names
labels = ['Non-review', 'Review papers']
sizes = perc_review['count']

pcts = [f'{l}\n({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(perc_review['count'], labels = pcts, labeldistance = 1.1, colors = ['#282828','#848484','#C0C0C0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(pub_type_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_perc_review.png', format = 'png', dpi=300);

"""# Plot of publications per type - missing export figure"""

# Get number of publications per year
pub_type = review_papers['publication_type'].value_counts()
pub_type = pd.DataFrame(pub_type)
pub_type = pub_type.reset_index()
pub_type.rename(columns = {'publication_type':'Publication Type'}, inplace = True)
pub_type

# Create a circle at the center of the plot
fig, ax = plt.subplots()
pub_type_circle = plt.Circle((0,0), 0.6, color='white')

# Give color names
labels = pub_type['Publication Type']
sizes = pub_type['count']

pcts = [f'{l}\n({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(pub_type['count'], labels = pcts, labeldistance = 1.1, colors = ['#282828','#848484','#C0C0C0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(pub_type_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_pub_type.png', format = 'png', dpi=300);

"""# Plot of publications per evidence type - missing export figure"""

# Get number of publications per year
evidence_type = db_noreviews['evidence_type'].value_counts()
evidence_type = pd.DataFrame(evidence_type)
evidence_type = evidence_type.reset_index()
evidence_type.rename(columns = {'evidence_type':'Evidence Type'}, inplace = True)
evidence_type

# Create a circle at the center of the plot
fig, ax = plt.subplots()
evidence_type_circle = plt.Circle((0,0), 0.6, color='white')

# Give color names
labels = evidence_type['Evidence Type']
sizes = evidence_type['count']

pcts = [f'{l}\n({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(evidence_type['count'], labels = pcts, labeldistance = 1.1, colors = ['#282828','#848484','#C0C0C0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(evidence_type_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_evidence_type.png', format = 'png', dpi=300);

"""# Barplot of climate regions"""

climate_zone = db_noreviews['climate_zone'].value_counts()
climate_zone = pd.DataFrame(climate_zone)
climate_zone = climate_zone.reset_index()

climate_zone

# Get number of climate zones
climate_zone = db_noreviews['climate_zone'].value_counts()
climate_zone = pd.DataFrame(climate_zone)
climate_zone = climate_zone.reset_index()
# climate_zone.rename(columns = {'index':'climate_zone', 'climate_zone':'count'}, inplace = True)

# Get number of lake thermal regions
thermal_region = db_noreviews['thermal_region'].value_counts()
thermal_region = pd.DataFrame(thermal_region)
thermal_region = thermal_region.reset_index()
# thermal_region.rename(columns = {'index':'thermal_region', 'thermal_region':'count'}, inplace = True)
thermal_region

fig, ax = plt.subplots(nrows = 1, ncols = 2, figsize = (13, 4), sharey = True)
barWidth = 0.5

# Climate zone
ax[0].bar(climate_zone['climate_zone'], climate_zone['count'], color='#515151', edgecolor='white', width = barWidth, alpha = 0.8)
# ax[0].hist(climate_zone['climate_zone'], edgecolor="black", color="#282828", align = 'mid' , alpha = 0.8)

ax[0].set_ylabel("Count of publications", size = 12)
ax[0].set_xlabel("Koppen-Geiger climate zones", size = 12)
ax[0].set_ylim(0,20)

ax[0].set_axisbelow(True)
ax[0].grid(color='lightgray', axis = 'y')

ax[0].text(12.1, 18, '(a)', color = 'k', size = 12)

# Lake thermal region
ax[1].bar(thermal_region['thermal_region'], thermal_region['count'], color='#8E8E8E', edgecolor='white', width = barWidth, alpha = 0.8)

ax[1].set_xlabel("Lake thermal region (Maberly et al. 2020)", size = 12)
# ax[1].set_ylim(0,16)

ax[1].set_axisbelow(True)
ax[1].grid(color='lightgray', axis = 'y')

ax[1].text(5.2, 18, '(b)', color = 'k', size = 12)

# Plot adjustments
plt.xticks(fontsize = 12)
plt.yticks(fontsize = 12)

plt.tight_layout()

# Save graph
plt.savefig(os.path.join(FIG_DIR, 'bar_zones_updated_search.jpeg'), format = 'jpeg', dpi=300);

"""# Water body type"""

# Get distribution of studies per water body type
wb_type = db_noreviews['waterbody_type'].value_counts()
wb_type = pd.DataFrame(wb_type)
wb_type = wb_type.reset_index()
wb_type.rename(columns = {'waterbody_type':'wb_type'}, inplace = True)
wb_type

# Create a circle at the center of the plot
# plt.switch_backend('agg') # line to export figure
fig, ax = plt.subplots()
wb_type_circle = plt.Circle((0,0), 0.6, color='white')

# Give color names
labels = wb_type['wb_type']
sizes = wb_type['count']

pcts = [f'{l} ({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(wb_type['count'], labels = pcts, labeldistance = 1.1, colors = ['#030303','#303030','#4A4A4A','#636363','#7F7F7F','#B3B3B3','#E0E0E0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(wb_type_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_wb_type.png', format = 'png', dpi=300);

"""# Hydropower"""

# Get distribution of studies per water body type
hydro_papers = db_noreviews['hydropower'].value_counts()
hydro_papers = pd.DataFrame(hydro_papers)
hydro_papers = hydro_papers.reset_index()
# hydro_papers.rename(columns = {'index':'hydropower', 'hydropower':'count'}, inplace = True)
hydro_papers

# Create a circle at the center of the plot
fig, ax = plt.subplots()
hydropower_circle = plt.Circle((0,0), 0.6, color='white')

# Give color names
labels = ['Other sites','Hydropower']
sizes = hydro_papers['count']

pcts = [f'{l} ({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(hydro_papers['count'], labels = pcts, labeldistance = 1.1, colors = ['#030303', '#E0E0E0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(hydropower_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_hydropower.png', format = 'png', dpi=300);

reviews = sum(review_complete['review'] == 'No')
reviews

"""# FPV - comparison with x without and before x after"""

## Get distribution of studies that have comparison with and without FPV + before and after deployment
# With x without
fpv_comparison = db_noreviews['with_without_fpv'].value_counts()
fpv_comparison = pd.DataFrame(fpv_comparison)
fpv_comparison = fpv_comparison.reset_index()
fpv_comparison.rename(columns = {'with_without_fpv':'fpv_comparison'}, inplace = True)

# Before x after deployment
fpv_bef_after = db_noreviews['bef_after_deploym'].value_counts()
fpv_bef_after = pd.DataFrame(fpv_bef_after)
fpv_bef_after = fpv_bef_after.reset_index()
fpv_bef_after.rename(columns = {'bef_after_deploym':'fpv_bef_after'}, inplace = True)
fpv_bef_after

# Create a circle at the center of the plot
fig, ax = plt.subplots(ncols = 1, nrows = 1, figsize = (6,4))
fpv_circle = plt.Circle((0,0), 0.6, color='white')

# With x without FPV
labels = ['With/without FPV','No With/without FPV']
sizes = fpv_comparison['count']

pcts = [f'{l}\n({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(fpv_comparison['count'], labels = pcts, labeldistance = 1.1, colors = ['#030303', '#E0E0E0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(fpv_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_fpv_with_without.png', format = 'png', dpi=300);

# Create a circle at the center of the plot
fig, ax = plt.subplots(ncols = 1, nrows = 1, figsize = (6,4))
fpv_circle = plt.Circle((0,0), 0.6, color='white')

# Before x after deployment
labels = ['No before/after FPV', 'With before/after FPV']
sizes = fpv_bef_after['count']

pcts = [f'{l}\n({s*100/sum(sizes):.1f}%)' for s,l in zip(sizes, labels)]

ax.pie(fpv_bef_after['count'], labels = pcts, labeldistance = 1.1, colors = ['#030303', '#E0E0E0'], wedgeprops = {'linewidth' : 4, 'edgecolor' : 'white'})
p = plt.gcf()
p.gca().add_artist(fpv_circle)

# Show the graph
plt.show()

# Save graph
# plt.savefig('donut_fpv_bef_after.png', format = 'png', dpi=300);

"""# Map with number of researches per country"""

# Get the unique countries and how many times they are on the table (i.e. how many studies per country)
countries = db_noreviews.country.value_counts()
countries = pd.DataFrame(countries)
countries = countries.reset_index()
# countries.rename(columns = {'count':'country', 'country':'count'}, inplace = True)

# Change USA for United States
countries['country'] = np.where(countries['country'] == 'USA', 'United States of America', countries['country'])
countries.head()

countries.to_csv(os.path.join(DATA_DIR, 'countries.csv'))

countries['country'].unique()

## Read the world's shapefile
# Setting the path to the shapefile
# NOTE: The Natural Earth 1:10m Admin 0 Countries shapefile is NOT included in
# this repository (it is a large, freely-available external dataset). Download
# it from naturalearthdata.com and place the .shp (and its companion files)
# under data/shapefiles/. See README.
SHAPEFILE = os.path.join(DATA_DIR, 'shapefiles', 'ne_10m_admin_0_countries.shp')

# Read shapefile using Geopandas
geo_df = gpd.read_file(SHAPEFILE)[['ADMIN', 'ADM0_A3', 'geometry']]

# Rename columns.
geo_df.columns = ['country', 'country_code', 'geometry']

# Drop row for 'Antarctica'. It takes a lot of space in the map and is not of much use
geo_df = geo_df.drop(geo_df.loc[geo_df['country'] == 'Antarctica'].index)

geo_df.head(3)

# Prepare dataframe to plot
# Define dataframes for vertical lookup (df1 will be kept the rows, while df2 will be looked for the df1's values, i.e. search df1 country on the df2 list to get the count)
df1 = geo_df
df2 = countries

Left_join = pd.merge(df1, df2, on ='country', how ='left')
Left_join.head()

Left_join['count'].max()

# Plot the country boundaries and the heatmap
# plt.switch_backend('agg') # line to export figure
ax = geo_df.plot(figsize = (11, 8), alpha = 0.5, edgecolor = 'k', facecolor = 'white')
Left_join.plot(ax = ax, markersize = 10, legend = True, vmax = 10, vmin = 0, column = 'count', cmap = 'coolwarm', legend_kwds = {'shrink': 0.45, 'label':'Count of publications'})

# ax.grid(True, linestyle = '-', linewidth = 0.5, color='gray', zorder = -1)

geometry = [Point(xy) for xy in zip(lakes_coords['longitude_E'], lakes_coords['latitude_N'])]
coords_sites = GeoDataFrame(lakes_coords, geometry=geometry)
coords_sites.plot(ax = ax, marker = '.', color = 'k', markersize=15);

# Customize the axis labels
ax.set_facecolor('white')
ax.tick_params(axis = 'x', labelsize = 12)
ax.xaxis.set_label_text('Longitude', size = 12)
ax.tick_params(axis = 'y', labelsize = 12)
ax.yaxis.set_label_text('Latitude', size = 12)

# Show the plot
plt.show()

plt.tight_layout()

# Save graph
plt.savefig(os.path.join(FIG_DIR, 'publications_map_updated_search.jpeg'), format = 'jpeg', dpi=300, bbox_inches='tight');

"""# Direction of change - graph"""

# Import file
direction_imp = pd.read_csv(os.path.join(DATA_DIR, 'impact_direction_format_updated.csv'))

# Create sum column to order
direction_imp['total'] = (direction_imp['increase_modelling'] + direction_imp['decrease_modelling'] + direction_imp['varies_modelling'] + direction_imp['no_change_modelling']) + (direction_imp['increase_empirical'] + direction_imp['decrease_empirical'] + direction_imp['varies_empirical'] + direction_imp['no_change_empirical'])
direction_imp = direction_imp.sort_values(by = 'total')

# Make data suitable for left/right plot
direction_imp['decrease_modelling'] = -direction_imp['decrease_modelling']
direction_imp['decrease_empirical'] = -direction_imp['decrease_empirical']

# Take zeros out of varies and no change columns
direction_imp['varies_modelling'] = direction_imp['varies_modelling'].replace({0:np.nan})
direction_imp['varies_empirical'] = direction_imp['varies_empirical'].replace({0:np.nan})
direction_imp['no_change_modelling'] = direction_imp['no_change_modelling'].replace({0:np.nan})
direction_imp['no_change_empirical'] = direction_imp['no_change_empirical'].replace({0:np.nan})
direction_imp.head()

# Create subset dataframes following classes
direc_imp_phy = direction_imp.loc[direction_imp['class'] == 'Physical']
direc_imp_chem = direction_imp.loc[direction_imp['class'] == 'Chemical']
direc_imp_bio = direction_imp.loc[direction_imp['class'] == 'Biological']

# Remove evaporation row from table
# direc_imp_phy = direc_imp_phy[direc_imp_phy['process'] != 'Evaporation']

# Remove contaminant and salinity - no evidence
direc_imp_phy = direc_imp_phy[direc_imp_phy['process'] != 'Salinity']
direc_imp_chem = direc_imp_chem[direc_imp_chem['process'] != 'Contaminant']

# Create plot
fig, ax = plt.subplots(figsize = (11,4.5))
ax.axis('off')
gs = GridSpec(3, 2, figure=fig)

# Chemical process
ax1 = fig.add_subplot(gs[:, 0])
class_graph = direc_imp_chem['process']
ax1.barh(direc_imp_chem['process'], direc_imp_chem['increase_empirical'], color = '#8F8F8F', label = 'Empirical')
ax1.barh(direc_imp_chem['process'], direc_imp_chem['increase_modelling'], left = direc_imp_chem['increase_empirical'], color = 'k', label = 'Modelling')

ax1.barh(direc_imp_chem['process'], direc_imp_chem['decrease_empirical'], color = '#8F8F8F')
ax1.barh(direc_imp_chem['process'], direc_imp_chem['decrease_modelling'], left = direc_imp_chem['decrease_empirical'], color = 'k')

ax1.set_xlim(-13,13)
ax1.xaxis.set_ticks(np.arange(-10, 11, 5))
ax1.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax1.get_xticks()])

ax1.text(-7, 11.2, 'Decrease', color = 'k')
ax1.text(2.5, 11.2, 'Increase', color = 'k')

ax1.set_axisbelow(True)
ax1.set_xlabel("Count of evidence record")

fig.text(0.1, 0.94, '(a) Chemical impacts', ha = 'center', size = 10, fontweight = 'bold')
ax1.axvline(0, 0, color = 'k')
ax1.grid()

# Physical process
ax2 = fig.add_subplot(gs[0:2, 1])
class_graph = direc_imp_phy['process']
ax2.barh(direc_imp_phy['process'], direc_imp_phy['increase_empirical'], color = '#8F8F8F', label = 'Empirical')
ax2.barh(direc_imp_phy['process'], direc_imp_phy['increase_modelling'], left = direc_imp_phy['increase_empirical'], color = 'k', label = 'Modelling')

ax2.barh(direc_imp_phy['process'], direc_imp_phy['decrease_empirical'], color = '#8F8F8F')
ax2.barh(direc_imp_phy['process'], direc_imp_phy['decrease_modelling'], left = direc_imp_phy['decrease_empirical'], color = 'k')

ax2.set_xlim(-20,10)
ax2.xaxis.set_ticks(np.arange(-20, 11, 5))
ax2.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax2.get_xticks()])

ax2.text(-13.7, 9.5, 'Decrease', color = 'k')
ax2.text(1.6, 9.5, 'Increase', color = 'k')

ax2.set_axisbelow(True)
ax2.legend(title = 'Evidence type', loc='upper left', bbox_to_anchor=(1, 1.04))

fig.text(0.55, 0.94, '(b) Physical impacts', ha = 'center', size = 10, fontweight = 'bold')
ax2.axvline(0, 0, color = 'k')
ax2.grid()

# Biological process
ax3 = fig.add_subplot(gs[2, 1])
class_graph = direc_imp_bio['process']
ax3.barh(direc_imp_bio['process'], direc_imp_bio['increase_empirical'], color = '#8F8F8F', label = 'Empirical')
ax3.barh(direc_imp_bio['process'], direc_imp_bio['increase_modelling'], left = direc_imp_bio['increase_empirical'], color = 'k', label = 'Modelling')

ax3.barh(direc_imp_bio['process'], direc_imp_bio['decrease_empirical'], color = '#8F8F8F')
ax3.barh(direc_imp_bio['process'], direc_imp_bio['decrease_modelling'], left = direc_imp_bio['decrease_empirical'], color = 'k')

ax3.set_xlim(-28,10)
ax3.xaxis.set_ticks(np.arange(-25, 11, 5))
ax3.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax3.get_xticks()])

ax3.text(-19, 2.95, 'Decrease', color = 'k')
ax3.text(1, 2.95, 'Increase', color = 'k')

ax3.set_axisbelow(True)
ax3.set_xlabel("Count of evidence record")

fig.text(0.55, 0.33, '(c) Biological impacts', ha = 'center', size = 10, fontweight = 'bold')
ax3.axvline(0, 0, color = 'k')
ax3.grid()

plt.tight_layout()

# Salvar o gráfico gerado
plt.savefig(os.path.join(FIG_DIR, 'direction_evidence_complete_updated_search.png'), dpi = 300)

# Create plot
f, (ax, ax2) = plt.subplots(1, 2, sharey=True, facecolor='w', figsize = (4.9,2.8),  gridspec_kw={'width_ratios': [0.3, 2]})

ax2.barh(direc_imp_phy['process'], direc_imp_phy['increase_empirical'], height = 0.6, color = '#8F8F8F', label = 'Empirical')
ax2.barh(direc_imp_phy['process'], direc_imp_phy['increase_modelling'], height = 0.6, left = direc_imp_phy['increase_empirical'], color = 'k', label = 'Modelling')

ax.barh(direc_imp_phy['process'], direc_imp_phy['decrease_empirical'], height = 0.6, color = '#8F8F8F')
ax.barh(direc_imp_phy['process'], direc_imp_phy['decrease_modelling'], height = 0.6, left = direc_imp_phy['decrease_empirical'], color = 'k')

ax2.barh(direc_imp_phy['process'], direc_imp_phy['decrease_empirical'], height = 0.6, color = '#8F8F8F')
ax2.barh(direc_imp_phy['process'], direc_imp_phy['decrease_modelling'], height = 0.6, left = direc_imp_phy['decrease_empirical'], color = 'k')

ax.set_xlim(-120, -110)
ax.xaxis.set_ticks(np.arange(-120, -109, 20))
ax.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax.get_xticks()])
ax2.set_xlim(-25, 10)
ax2.xaxis.set_ticks(np.arange(-25, 11, 5))
ax2.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax2.get_xticks()])

ax.spines['right'].set_visible(False)
ax2.spines['left'].set_visible(False)
ax2.yaxis.tick_left()

# Clip x axis to improve visualization
d = .015 # how big to make the diagonal lines in axes coordinates
kwargs = dict(transform=ax.transAxes, color = 'k', clip_on = False)
ax.plot((1-d, 1+d), (-d, +d), **kwargs)
ax.plot((1-d, 1+d), (1-d, 1+d), **kwargs)
kwargs.update(transform=ax2.transAxes)  # switch to the bottom axes
ax2.plot((-d, +d), (1-d, 1+d), **kwargs)
ax2.plot((-d, +d), (-d, +d), **kwargs)

# ax2.text(-19, 9.8, 'Decrease', color = 'k')
# ax2.text(4.5, 9.8, 'Increase', color = 'k')

ax.set_axisbelow(True)
ax2.set_axisbelow(True)
# ax2.set_xlabel("Count of evidence record")

ax2.axvline(0, 0, color = 'k')
ax.grid()
ax2.grid()

# ax2.legend(title = 'Evidence type', loc='upper left', bbox_to_anchor=(1, 1.02))
# ax2.legend(title = 'Evidence type', loc='upper right')

# ax.margins(y=0.03, x = 0.03)

plt.tight_layout()

# Salvar o gráfico gerado
plt.savefig(os.path.join(FIG_DIR, 'physical_direction_updated_search.jpeg'), dpi=300, transparent = True)

"""# Direction of impact - Categories (CHE - PHY - BIO)"""

evidence_clean = direction_imp[direction_imp['total'] > 4]
evidence_clean = evidence_clean.sort_values(by = 'class', ascending=False)
evidence_clean

# Create plot
f, (ax, ax2) = plt.subplots(1, 2, sharey=True, facecolor='w', figsize = (9,5),  gridspec_kw={'width_ratios': [0.3, 2]})

ax2.barh(evidence_clean['process'], evidence_clean['increase_empirical'], height = 0.6, color = '#8F8F8F', label = 'Empirical')
ax2.barh(evidence_clean['process'], evidence_clean['increase_modelling'], height = 0.6, left = evidence_clean['increase_empirical'], color = 'k', label = 'Modelling')

ax.barh(evidence_clean['process'], evidence_clean['decrease_empirical'], height = 0.6, color = '#8F8F8F')
ax.barh(evidence_clean['process'], evidence_clean['decrease_modelling'], height = 0.6, left = evidence_clean['decrease_empirical'], color = 'k')

ax2.barh(evidence_clean['process'], evidence_clean['decrease_empirical'], height = 0.6, color = '#8F8F8F')
ax2.barh(evidence_clean['process'], evidence_clean['decrease_modelling'], height = 0.6, left = evidence_clean['decrease_empirical'], color = 'k')

ax.set_xlim(-120, -110)
ax.xaxis.set_ticks(np.arange(-120, -109, 20))
ax.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax.get_xticks()])
ax2.set_xlim(-25, 15)
ax2.xaxis.set_ticks(np.arange(-28, 16, 5))
ax2.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax2.get_xticks()])

ax.spines['right'].set_visible(False)
ax2.spines['left'].set_visible(False)
ax2.yaxis.tick_left()

# Clip x axis to improve visualization
d = .015 # how big to make the diagonal lines in axes coordinates
kwargs = dict(transform=ax.transAxes, color = 'k', clip_on = False)
ax.plot((1-d, 1+d), (-d, +d), **kwargs)
ax.plot((1-d, 1+d), (1-d, 1+d), **kwargs)
kwargs.update(transform=ax2.transAxes)  # switch to the bottom axes
ax2.plot((-d, +d), (1-d, 1+d), **kwargs)
ax2.plot((-d, +d), (-d, +d), **kwargs)

ax2.text(-19, 12.1, 'Decrease', color = 'k')
ax2.text(4.5, 12.1, 'Increase', color = 'k')

ax.set_axisbelow(True)
ax2.set_axisbelow(True)
# ax2.set_xlabel("Count of evidence record")

ax2.axvline(0, 0, color = 'k')
ax.grid()
ax2.grid()

ax.axhline(y = 7.5, xmin = -1, xmax = -1, c = "k", linewidth = 2, linestyle = '--', zorder = 0, clip_on = False)
ax2.axhline(y = 7.5, xmin = -0.65, xmax = 0.995, c = "k", linewidth = 2, linestyle = '--', zorder = 0, clip_on = False)

ax.axhline(y = 2.53, xmin = -1, xmax = -1, c = "k", linewidth = 2, linestyle = '--', zorder = 0, clip_on = False)
ax2.axhline(y = 2.53, xmin = -0.65, xmax = 0.995, c = "k", linewidth = 2, linestyle = '--', zorder = 0, clip_on = False)

ax.text(-155, -0.05, '(a) Physical', ha = 'center', size = 9, rotation = 90, fontweight = 'bold')
# ax.text(-87, -0.45, 'Biological', ha = 'center', size = 10, rotation = 90, fontweight = 'bold')
ax.text(-155, 4.1, '(b) Chemical', ha = 'center', size = 9, rotation = 90, fontweight = 'bold')
ax.text(-155, 7.8, '(c) Biological', ha = 'center', size = 9, rotation = 90, fontweight = 'bold')

# ax2.legend(title = 'Evidence type', loc='upper left', bbox_to_anchor=(1, 1.02))
ax2.legend(title = 'Evidence type', loc='upper right')

f.text(0.53, -0.01, "Count of evidence record", ha = 'center', size = 12)

ax.margins(y=0.03, x = 0.03)

plt.tight_layout()

# Salvar o gráfico gerado
plt.savefig(os.path.join(FIG_DIR, 'direction_evidence_morethan5_updated_search.jpeg'), dpi=300, bbox_inches='tight')

"""# Frequency analysis - Lakes constituents and processes"""

# Import files
processes_frequency_count = pd.read_csv(os.path.join(DATA_DIR, 'processes_frequency_count_updated_search.csv'))
processes_frequency_count.head()

# Create subset dataframes following classes
freq_physical = processes_frequency_count.loc[processes_frequency_count['class'] == 'Physical']
freq_chemical = processes_frequency_count.loc[processes_frequency_count['class'] == 'Chemical']
freq_biological = processes_frequency_count.loc[processes_frequency_count['class'] == 'Biological']

# Create plot
fig, ax = plt.subplots(figsize = (8,3.5))
ax.axis('off')
gs = GridSpec(3, 2, figure=fig)

# Chemical process
ax1 = fig.add_subplot(gs[:, 0])
class_graph = freq_chemical['process']
hbars = ax1.barh(freq_chemical['process'], freq_chemical['yes'], color = '#8F8F8F', label = 'Chemical')

ax1.set_xlim(0,65)
ax1.xaxis.set_ticks(np.arange(0, 66, 10))
ax1.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax1.get_xticks()])

ax1.set_axisbelow(True)
ax1.set_xlabel("Count of evidence record")

fig.text(0.49, 0.9, '(a) Chemical', ha = 'center', size = 10)

ax1.bar_label(hbars, padding = 5)

# Physical process
ax2 = fig.add_subplot(gs[0:2, 1])
class_graph = freq_physical['process']
hbars = ax2.barh(freq_physical['process'], freq_physical['yes'], color = '#8F8F8F', label = 'Physical')

ax2.set_xlim(0,65)
ax2.xaxis.set_ticks(np.arange(0, 66, 10))
ax2.set_xticklabels([])
# ax2.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax2.get_xticks()])

ax2.set_axisbelow(True)

fig.text(0.91, 0.9, '(b) Physical', ha = 'center', size = 10)

ax2.bar_label(hbars, padding = 5)

# Biological process
ax3 = fig.add_subplot(gs[2, 1])
class_graph = freq_biological['process']
hbars = ax3.barh(freq_biological['process'], freq_biological['yes'], color = '#8F8F8F', label = 'Biological')

ax3.set_xlim(0,65)
ax3.xaxis.set_ticks(np.arange(0, 66, 10))
ax3.set_xticklabels(["{0:.0f}".format(abs(x)) for x in ax3.get_xticks()])

ax3.set_axisbelow(True)
ax3.set_xlabel("Count of evidence record")

fig.text(0.91, 0.335, '(c) Biological', ha = 'center', size = 10)

ax3.bar_label(hbars, padding = 5)

plt.tight_layout()

# Salvar o gráfico gerado
plt.savefig(os.path.join(FIG_DIR, 'processes_frequency_count_updated_search.jpeg'), dpi = 300)

# Plot
# Create a circle at the center of the plot
fig, ax = plt.subplots(ncols = 1, nrows = 1, figsize = (5.5,6))

# Increase and decrease side
hbars = ax.barh(processes_frequency_count['process'], processes_frequency_count['yes'], color = '#8F8F8F')

ax.set_xlim(0,65)
ax.xaxis.set_ticks(np.arange(0, 66, 10))

ax.bar_label(hbars, padding = 5)

ax.set_axisbelow(True)
ax.set_xlabel("Frequency of record\nin publications", fontsize = 12)

ax.grid(which = 'major', color='#B3B3B3', axis = 'x', linestyle = '-')

plt.yticks(fontsize = 12)
plt.xticks(fontsize = 12)

# ax.minorticks_on()

plt.tight_layout()

# Salvar o gráfico gerado
plt.savefig(os.path.join(FIG_DIR, 'joined_processes_frequency_count_updated_search.jpeg'), dpi=300)